name: C Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the application
        run: ./assemble.sh hello.asm hello

      - name: Run tests
        run: ./test.sh
